name: Build and Deploy Site

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install C++ compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Build site generator
        run: |
          g++ -std=c++17 -Iinclude src/main.cpp src/markdown_parser.cpp -o site_generator
          chmod +x site_generator

      - name: Generate site
        run: ./site_generator

      - name: List generated files
        run: ls -la docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true